-- MySQL Script generated by MySQL Workbench
-- Wed Apr 24 16:11:59 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `login_usuario` VARCHAR(45) NOT NULL,
  `email_usuario` VARCHAR(45) NOT NULL,
  `senha_usuario` VARCHAR(45) NOT NULL,
  `deleted_usario` INT(1) ZEROFILL NOT NULL,
  `local_usuario` VARCHAR(45) NULL,
  `bio_usuario` VARCHAR(140) NULL,
  `link_usuario` VARCHAR(45) NULL,
  `company_usuario` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pergunta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Pergunta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Pergunta` (
  `id_pergunta` INT NOT NULL AUTO_INCREMENT,
  `titulo_pergunta` VARCHAR(150) NOT NULL,
  `dt_pergunta` DATETIME NOT NULL,
  `nick_pergunta` VARCHAR(20) NOT NULL,
  `desc_pergunta` VARCHAR(400) NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_pergunta`),
  INDEX `fk_id_usuario_Pergunta_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_id_usuario_Pergunta`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Resposta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Resposta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Resposta` (
  `id_resposta` INT NOT NULL AUTO_INCREMENT,
  `id_pergunta` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_resposta`),
  INDEX `fk_id_pergunta_Resposta_idx` (`id_pergunta` ASC) VISIBLE,
  INDEX `fk_id_usuario_Resposta_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_id_pergunta_Resposta`
    FOREIGN KEY (`id_pergunta`)
    REFERENCES `mydb`.`Pergunta` (`id_pergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_usuario_Resposta`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Favorito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Favorito` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Favorito` (
  `id_favorito` INT NOT NULL AUTO_INCREMENT,
  `id_pergunta` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_favorito`),
  INDEX `fk_id_pergunta_Favorito_idx` (`id_pergunta` ASC) VISIBLE,
  INDEX `fk_id_usuario_Favorito_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_id_pergunta_Favorito`
    FOREIGN KEY (`id_pergunta`)
    REFERENCES `mydb`.`Pergunta` (`id_pergunta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_usuario_Favorito`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`Usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
